version: '3.3'
services:
    backend:
        image: node:22
        volumes:
            - ./:/app
        working_dir: /app
        ports:
            - ${APP_PORT}:${APP_PORT}
        # command: sh -c "yarn &&
        #   yarn run db:migrate &&
        #   yarn run start:dev"
        command: sh -c "yarn run start:dev"
        env_file:
            - ./.env
        depends_on:
            - database

    database:
        image: postgis/postgis
        volumes:
            - /data/postgres:/data/postgres
        environment:
            - POSTGRES_PASSWORD=${DB_PSWD}
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
        ports:
            - 5432:5432

    redis:
        image: bitnami/redis:7.4.0
        ports:
            - '${REDIS_PORT}:6379'
        volumes:
            - /data/redis-persistence:/bitnami/redis/data
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
