version: '3.3'
services:
  backend:
    image: node:22
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: sh -c "yarn &&
      yarn run db:migrate &&
      yarn run start:dev"
    env_file:
      - ./.env
    depends_on:
      - database

  database:
    image: postgis/postgis
    volumes:
      - /data/postgres:/data/postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - 5432:5432
